export const venues = [
  {
    id: 1,
    name: "The Lantern Theatre",
    city: "Bristol",
    contact: "Alex Morgan",
    email: "alex@example.com",
    capacity: 240,
    parking:
      "Loading bay on Willow Lane; arrange access with the duty manager.",
    tech: "End-on stage, 8m × 6m. Lighting and sound specification to be confirmed.",
  },
  {
    id: 2,
    name: "Riverside Arts",
    city: "Oxford",
    contact: "Sam Taylor",
    email: "sam@example.com",
    capacity: 180,
    parking: "Two artist spaces behind the venue.",
    tech: "Black box studio, 6m × 5m; step-free loading.",
  },
  {
    id: 3,
    name: "Northgate Playhouse",
    city: "York",
    contact: "Jamie Reed",
    email: "jamie@example.com",
    capacity: 320,
    parking: "Use the east entrance for unloading.",
    tech: "Proscenium stage; request current technical pack.",
  },
  {
    id: 4,
    name: "The Assembly Room",
    city: "Bath",
    contact: "Robin Ellis",
    email: "robin@example.com",
    capacity: 150,
    parking: "Public car park nearby; loading by appointment.",
    tech: "Flexible seating. Portable PA available.",
  },
];
export const companies = [
  {
    id: 1,
    name: "Paper Moon Theatre",
    contact: "Charlie Lane",
    email: "charlie@example.com",
    services: "Tour booking · Promotion · Administration",
  },
  {
    id: 2,
    name: "Moving Stories",
    contact: "Jess Parker",
    email: "jess@example.com",
    services: "Producing · Tour booking · Promotion",
  },
  {
    id: 3,
    name: "Small Hours Company",
    contact: "Casey Blake",
    email: "casey@example.com",
    services: "Tour booking · Administration",
  },
];
export const productions = [
  {
    id: 1,
    name: "The Last Lighthouse",
    companyId: 1,
    description:
      "A warm, intimate story of home, hope and a light that never goes out.",
    assets: "Marketing pack requested",
  },
  {
    id: 2,
    name: "Between the Lines",
    companyId: 2,
    description:
      "An inventive movement performance exploring the stories we leave untold.",
    assets: "Images and copy ready",
  },
  {
    id: 3,
    name: "A Little More Time",
    companyId: 3,
    description: "A playful new comedy about friendship and second chances.",
    assets: "Artwork in progress",
  },
];
export const seedBookings = [
  {
    id: 1,
    productionId: 1,
    venueId: 1,
    date: "2026-11-06",
    time: "19:30",
    status: "Confirmed",
    deal: "£800 guarantee or 70% of net box office, whichever is greater",
    getIn: "14:00",
    getOut: "22:30",
    contract: "Awaiting signature",
    marketing: "Requested",
    task: "Chase signed contract",
    due: "2026-10-12",
    done: false,
    publish: true,
    ticketUrl: "",
    notes: "Artist and venue have agreed. Confirm dressing room access.",
    report: "Not due",
    amount: "",
    payment: "Not invoiced",
  },
  {
    id: 2,
    productionId: 2,
    venueId: 2,
    date: "2026-11-12",
    time: "19:00",
    status: "Pencilled",
    deal: "70/30 split — deductions to be agreed",
    getIn: "13:00",
    getOut: "22:00",
    contract: "Not started",
    marketing: "Not sent",
    task: "Confirm date with artist",
    due: "2026-10-09",
    done: false,
    publish: false,
    ticketUrl: "",
    notes: "Venue holding the date until Friday.",
    report: "Not due",
    amount: "",
    payment: "Not invoiced",
  },
  {
    id: 3,
    productionId: 1,
    venueId: 3,
    date: "2026-11-20",
    time: "19:30",
    status: "Confirmed",
    deal: "£950 guarantee",
    getIn: "14:30",
    getOut: "22:30",
    contract: "Signed",
    marketing: "Sent",
    task: "Send artist briefing",
    due: "2026-11-06",
    done: false,
    publish: true,
    ticketUrl: "",
    notes: "Check travel time from the previous performance.",
    report: "Not due",
    amount: "",
    payment: "Not invoiced",
  },
  {
    id: 4,
    productionId: 3,
    venueId: 4,
    date: "2026-12-03",
    time: "20:00",
    status: "Placeholder",
    deal: "To be discussed",
    getIn: "",
    getOut: "",
    contract: "Not started",
    marketing: "Not sent",
    task: "Follow up with programmer",
    due: "2026-10-14",
    done: false,
    publish: false,
    ticketUrl: "",
    notes: "Initial conversation after the autumn mailout.",
    report: "Not due",
    amount: "",
    payment: "Not invoiced",
  },
];
